In [1]:
from classo.solve_R2 import pathlasso_R2, Classo_R2, problem_R2
from classo.solve_R1 import pathlasso_R1, Classo_R1, problem_R1
from classo import random_data
import numpy as np

m,d,d_nonzero,k,sigma =5,10,2,0,0.5
matrices,sol = random_data(m,d,d_nonzero,k,sigma,zerosum=True,seed=5)

In [2]:
rho = 1.5 
lambdas = np.linspace(1.,1e-1,80)
pb = problem_R2(matrices,'DR',rho)

r = pb.lambdamax/(2*rho)
pb.compute_param()

In [3]:
pb.init_R1()
pb.add_r(r=r)
pb1 = pb.prob_R1

In [4]:
pb.init_R1(r=r)
pb2 = pb.prob_R1

In [ ]:
s1 = pb1.Aty
s2 = pb2.Aty
AtA1 = pb1.AtA
AtA2 = pb2.AtA
beta1 = Classo_R1(pb1, 0.1)[:d]
beta2 = Classo_R1(pb2, 0.1)[:d]

In [15]:
print(AtA1-AtA2)
print(s1-s2)
print(np.linalg.norm(beta1-beta2))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
2.5434175328256496
53.3520814155607
